### ISSUE TITLE
Error: No Civi Group ID could be found for bp-groups-civicrm-sync

### ISSUE THREAD

**Issue by danaskallman** [christianwach/bp-groups-civicrm-sync#1]
I am trying to test and set this us to sync BP group contacts. When I am trying to create a new group now I get this error: No Civi Group ID could be found for bp-groups-civicrm-sync

I get the same error when I try save settings in network admin to Use Parent Group. Thoughts on why that is? 

It is a WP 4.2.2 multisite with BP 2.3.2.1 and Civi 4.6.4

Thanks@

**Comment by christianwach** [comment]
I think I've found the source of the error. When the plugin is first installed, it doesn't create the Civi parent group, so you have to manually uncheck "Use Parent Group", hit "Save Changes", then re-check it to create it and hit "Save Changes" again. Thereafter everything works as expected, except that Civi 4.6.n in my test install doesn't show the child groups when the discovery tab is clicked :-(

Given this, I'd recommend not using the "Use Parent Group" option.

If you have created any BP groups, your DB will be out-of-sync, so you'll have to start afresh. Sorry about that. I'll set the default in the plugin not to "Use Parent Group" for now.

**Comment by danaskallman** [comment]
That fixed, works as noted now. Thanks!

**Comment by christianwach** [comment]
Good to hear @danaskallman. Do you also see what I saw - "Civi 4.6.n in my test install doesn't show the child groups when the discovery tab is clicked"? If so, I'll open a ticket for that.

**Comment by danaskallman** [comment]
@christianwach can you clarify what you mean by the discovery tab? I am unsure what I am to look for and test.

**Comment by christianwach** [comment]
It's the little triangle to the left of an item that, when clicked on, points downward and reveals sub-items. In this case, clicking on it should reveal the child groups of the "BuddyPress Groups" item, but (at least for me) does not.
