### ISSUE TITLE
Initial Sync Timing out

### ISSUE THREAD

**Issue by kcristiano** [christianwach/bp-groups-civicrm-sync#2]
We have a small sync - 25 BP Groups, yet it times out and we only get 13 orf the 25 syncd to Civi.

Yiou mention that we may want to chunk this to make it work.  Any suggstions on how to do that?  Would love to be able to run via the cli (wp-cli) as timeouts would not come in to play (as much).

**Comment by christianwach** [comment]
As you note, I was going to write an AJAX-driven interface for this, but never got round to it. [Something like this](https://wisdmlabs.com/blog/create-real-time-progress-bar-using-jquery-ui-ajax/) would probably do the trick with some tweaking. Process would be along these lines:
1. Add event listener to submit button
2. Make AJAX call and wait for response
3. PHP receives call, processes (say) 1 group, stores progress in database
4. On response, update progress bar
5. Goto 2 until PHP has processed all groups

Alternatively, without Javascript:
1. Show "Start Sync" button on initial load
2. Store group-ids-to-sync in a "total" option
3. Process first chunk, store "marker" option
4. Reload page showing "Continue Sync" button
5. Process next chunk, store marker
6. Goto 4 until PHP has processed all groups
7. Remove "total" and "marker" options

Presumably you'd do that with WP-CLI in a similar way, except that the function called would return a value indicating whether it needs to be called again or not.

**Comment by christianwach** [comment]
@kcristiano The master branch now includes the AJAX-driven interface. I'll release 0.2.2 to the WordPress repo shortly.

**Comment by kcristiano** [comment]
Thanks.   I'll pull and test

**Comment by kcristiano** [comment]
works perfectly thank you
