### ISSUE TITLE
Sync from Civi to BP : No OG Groups found (while Civi has groups)

### ISSUE THREAD

**Issue by jbonlinea** [christianwach/bp-groups-civicrm-sync#3]
Hi

I guess most is in the title :)

I have a new wp+civi instance
I created two groups in Civi, public mailing groups

They do not apear in BP group

When trying to sync them from the plug-in settings, it get No OG Groups found.

I did try to set "Use Parent Group"; I don't want/need it so I simply clicked on save changes without checking the checkbox, then sync again, but it do not change what described above.

However if I create a group from BP, it do create its "connected" Civi group (ACL and Mailing)

Then, in Civi I can add a membre to the mailing group, he indeed apears in the "connected" BP group.

I don't belive it's a bug per se, but somehting is wrong somewhere.

Do you have any ideas ?

Thank's

---
in wp site health i do have the well known error 

The REST API encountered an error
Error: [] cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received

---
wp 5.4.1
Civi 5.23.3
BP 6.0.0
bp-group-civicrm-sync 0.3.6
php 7.3

**Comment by christianwach** [comment]
@jbonlinea The plugin (at present) only allows synced groups to be created in BuddyPress. There is code in the plugin that I was working on to allow BuddyPress groups to be created when creating CiviCRM groups, but I didn't ever finish it.

The "Check for OG groups" option is for porting CiviCRM from Drupal to WordPress where CiviCRM has groups that were once synced to Drupal Organic Groups. I realise this is probably a bit misleading for people unfamiliar with the plugin.

FYI, if you want to allow only certain BuddyPress groups to be synced, then the following should get you started:

```php
add_filter( 'bp_groups_civicrm_sync_group_should_be_synced', 'my_groups_sync_filter', 10, 2 );
function my_groups_sync_filter( $should_be_synced, $group_id ) {
	$groups_to_sync = [1, 3]; // The IDs of the BuddyPress groups that *should* be synced.
	if ( ! in_array( $group_id, $groups_to_sync ) ) $should_be_synced = false;
	return $should_be_synced;
}
```

**Comment by jbonlinea** [comment]
Hi @christianwach 

Thank you very much for your reply !

and for this sniplet  !

I do have a tricky question thow how about smart group ? 

Thank's in advance

**Comment by christianwach** [comment]
@jbonlinea I have looked into this. Unfortunately Smart Groups can't be of type "Access Control" so there can't be a "paired" *Administrator* group like this plugin uses.

**Comment by jbonlinea** [comment]
hi, 

I felt it wasn't designed for that ! 
I'm abit puzzedle as most groups I intended to use were smart groups. 

I do not so much intend to use BP as a social network where people create groupes, but rathe as a front end profile module for CiviCrm contacts and groups !

Side questions thus, do you have any guidance or recomendation (readings, modules, etc) to display CiviCRM contact and group in WP front end ? Creating directories, etc...

I also wonder how are you using WP modules [members](https://wordpress.org/plugins/members/) and [groups](https://wordpress.org/plugins/groups/), and if you have any workflow to suggest ? (I've seen in the doc of you civicrm member sync module that you at least considered the two module I mention here)

Thank's foyr your attention and great developement, they are really game changer for anyone using wp with civicrm
