### ISSUE TITLE
Sync is not working anymore from BP 12.4 to CiviCRM

### ISSUE THREAD

**Issue by Guydn** [christianwach/bp-groups-civicrm-sync#5]
Hello Christian,

A client is reporting an issue on the sync.
- CiviCRM -> BP works  (real time)
- BP 12.4 -> CiviCRM does not work (real time)

Conf is WP 6.5.2. Civi 5.65 bp-groups-civicrm-snc 0.5.1

I do not have the exact time when the sync stopped (the client reported an issue lately) but I suppose it is linked to the migration I performed a few months ago.

Manual sync is working. The batch setting is BP -> Civi once a day.

**Comment by christianwach** [comment]
@Guydn Can you be a bit more specific about what "does not work" means?

I've just checked my local dev site and can't find a situation where sync doesn't work from BP to CiviCRM. I tried:

* User joins/leaves a group
* Group admin removes User from a group
* Group admin promotes/demotes Member to Mod
* Group admin promotes/demotes Mod to Admin
* Group admin promotes/demotes Admin to Mod/Member
* Site admin does all the above via the WordPress admin

Have I missed something?

**Comment by Guydn** [comment]
Hum... 
Settings for the "batch" part is
![BP groups Sync 1](https://github.com/christianwach/bp-groups-civicrm-sync/assets/35797460/0294050f-e814-4650-9906-137f82326e11)

- As a group admin, when I change (demote) a user in BP from admin to Member, there is no change in Civi (real time) (the user is still in the group ... administrator)
- As group admin, when I promote a user in BP from Member to admin, no change as well (in that case the user should belong to a new group)
- As a group admin, when I remove a user, no change in Civi (the user still belongs to the group)
- As a user, when I join / leave a group, it is OK in Civi

Strange...

**Comment by christianwach** [comment]
@Guydn FYI the "Recurring Schedules" setting doesn't have any immediate effect on sync - what it does is to "repair" any statuses that have got out of sync for some reason. This is more useful in a CiviCRM--to-BuddyPress context because there have been reports of edge cases where CiviCRM hooks do not fire.

So are you using BP Nouveau? What I'm seeing in the latest BuddyPress is that when updating Group Memberships on a Group's front-end "Manage Members" screen, BP Nouveau performs the status update via a BuddyPress REST API endpoint - and this does not appear to fire the usual family of BuddyPress actions - `groups_promoted_member`, `groups_demoted_member` etc etc. Oh dear.

The question now is whether BuddyPress should fire the usual actions or whether this plugin should try and work without them... Hmm...

**Comment by Guydn** [comment]
OK with your first point. I was not aware of these edge cases. It is anyhow important to have he possibility to repair "in case".  With my setting, i am able to align daily data between Civi and BP. So that it is a good workaround :-).

I have migrated to 12.5.0. I get now strange messages in BP

A user can join a public group (and Civi is OK)
As a group admin when I want to promote as "admin", I get a message saying that it is not possible...
As a group admin when I want to demote from admin to member, I get the same message.
In my test, I am not only a group admin but also a WP admin, so it is not a permission issue.

It seems that the BP Rest API does not work. So I think it is an issue on BP side. I am going to report that on their side. Thanks a lot !

**Comment by christianwach** [comment]
> As a group admin when I want to promote as "admin", I get a message saying that it is not possible...
> As a group admin when I want to demote from admin to member, I get the same message.
> In my test, I am not only a group admin but also a WP admin, so it is not a permission issue.

Hmm, I get the opposite - BuddyPress Nouveau allows me to demote _all_ group admins so that there are none left. BP Classic does not allow this. Well, either way there's something messed up.

Have you considered using BP Classic instead? AFAICT it works as it should.

**Comment by christianwach** [comment]
I have opened https://buddypress.trac.wordpress.org/ticket/9158

**Comment by Guydn** [comment]
Thanks a lot ! I saw your ticket was acknowledged ! 

I hope they will be able to fix the stability as well.
When I promote from member to admin, I see the change. If I refresh the browser tab, the change does not seem to be taken in account. When I change again (member to admin), then I have a message saying it is not possible.
When I open a new browser window, the change is actually OK. 
When users reported this issue, I was puzzled because I told them the change was recorded.

**Comment by christianwach** [comment]
Urgh, doesn't sound good at all. Like I said, perhaps try BP Classic in the meantime?

**Comment by Guydn** [comment]
Actually, I changed the template pack BuddyPress from "Nouveau" to "Héritage" which I assume is "classic". I had 404 errors so i rolled back to Nouveau.

I see that BP has a fix. I will wait then until the version is available on the platform. I am on the last available one 12.5.0

Thanks again for your support :-).

**Comment by Guydn** [comment]
I have just updated BP to new version 14.0.0 (available since a few days ago). 
Your ticket is included https://buddypress.trac.wordpress.org/ticket/9158. 
It is solved ! This ticket can be closed. Thanks a lot .
